import useMovies from "../hooks/useMovies";
import useLanguage from "../hooks/useLanguage";

export default function About() {
  const { movies, siteSettings } = useMovies();
  const { t } = useLanguage();
  const genreCount = new Set(movies.map((movie) => movie.genre)).size;
  const values = [
    [
      "01",
      t("humanCurated", "Human curated"),
      t(
        "humanCuratedCopy",
        "Every film is selected with care, not generated by an endless algorithm.",
      ),
    ],
    [
      "02",
      t("qualityFirst", "Quality first"),
      t(
        "qualityFirstCopy",
        "We focus on storytelling, craft and films with lasting value.",
      ),
    ],
    [
      "03",
      t("simpleDiscovery", "Simple discovery"),
      t(
        "simpleDiscoveryCopy",
        "Designed to help you find a great film without endless scrolling.",
      ),
    ],
  ];

  return (
    <main className="page-shell about-page">
      <div className="container">
        <section className="about-hero">
          <img src="/images/banners/cinema-banner.webp" alt="" />
          <div className="about-hero-overlay" />
          <div className="about-hero-copy">
            <span className="eyebrow">{t("ourView", "Our point of view")}</span>
            <h1>{t("aboutHeading", siteSettings.aboutHeading)}</h1>
            <p>
              {t(
                "aboutHeroCopy",
                "We collect films with powerful stories, beautiful images and feelings that stay with you.",
              )}
            </p>
          </div>
          <div className="about-hero-index">
            <span>EST.</span>
            <b>2026</b>
          </div>
        </section>

        <section className="about-manifesto">
          <div>
            <span className="eyebrow">{t("whyExist", "Why we exist")}</span>
            <h2>{t("lessScrolling", "Less scrolling. More feeling.")}</h2>
          </div>
          <div>
            <p>{t("aboutCopy", siteSettings.aboutCopy)}</p>
            <p>
              {t(
                "aboutHeroCopy",
                "We believe choosing what to watch should feel inspiring, not exhausting.",
              )}
            </p>
          </div>
        </section>

        <section className="about-stat-grid">
          <div>
            <small>01</small>
            <b>{movies.length}</b>
            <span>{t("curatedTitles", "Curated titles")}</span>
          </div>
          <div>
            <small>02</small>
            <b>{genreCount}</b>
            <span>{t("distinctGenres", "Distinct genres")}</span>
          </div>
          <div>
            <small>03</small>
            <b>100%</b>
            <span>{t("reactPowered", "React powered")}</span>
          </div>
        </section>

        <section className="about-values">
          <header>
            <span className="eyebrow">{t("ourApproach", "Our approach")}</span>
            <h2>{t("qualityFirst", "Made with intention.")}</h2>
          </header>
          <div className="about-value-grid">
            {values.map(([number, title, copy]) => (
              <article key={number}>
                <span>{number}</span>
                <i />
                <h3>{title}</h3>
                <p>{copy}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="about-cta">
          <span className="eyebrow">
            {t("startConversation", "Start a conversation")}
          </span>
          <h2>{t("beginConversation", "Know a film we should see?")}</h2>
          <p>
            {t(
              "beginConversationCopy",
              "Share a recommendation, send feedback, or simply talk cinema with us.",
            )}
          </p>
          <a className="btn btn-primary" href="/contact">
            {t("talkToUs", "Talk to us")} <span>↗</span>
          </a>
        </section>
      </div>
    </main>
  );
}
