import { createContext, useEffect, useMemo } from "react";
import useLocalStorage from "../hooks/useLocalStorage";

const translations = {
  home: "ទំព័រដើម",
  movies: "ភាពយន្ត",
  favourites: "ចំណូលចិត្ត",
  watchlist: "បញ្ជីមើល",
  about: "អំពីយើង",
  dashboard: "ផ្ទាំងគ្រប់គ្រង",
  signIn: "ចូលគណនី",
  signOut: "ចាកចេញ",
  uploadPicture: "បញ្ចូលរូបភាព",
  remove: "លុប",
  search: "ស្វែងរក",
  closeSearch: "បិទការស្វែងរក",
  editorSelection: "ជម្រើសរបស់អ្នកកែសម្រួល",
  comingSoon: "មកដល់ឆាប់ៗ",
  watchTrailer: "មើលឈុតខ្លី",
  watchMovie: "មើលភាពយន្ត",
  myWatchlist: "បញ្ជីមើលរបស់ខ្ញុំ",
  filmDetails: "ព័ត៌មានភាពយន្ត",
  upNext: "បន្ទាប់",
  scrollDiscover: "រំកិលដើម្បីស្វែងរក",
  explore: "ស្វែងរក",
  exploreAll: "មើលទាំងអស់",
  curatedTonight: "ជ្រើសរើសសម្រាប់យប់នេះ",
  curatedCopy: "រឿងដែលបានជ្រើសរើសដោយយកចិត្តទុកដាក់",
  films: "ភាពយន្ត",
  genres: "ប្រភេទ",
  topScore: "ពិន្ទុខ្ពស់",
  browseVault: "មើលបណ្ណាល័យ",
  audienceScore: "ពិន្ទុអ្នកទស្សនា",
  editorsCut: "ជម្រើសពិសេស",
  worthNight: "ភាពយន្តមួយ ដែលស័ក្តិសមសម្រាប់រាត្រីនេះ",
  genre: "ប្រភេទ",
  released: "ឆ្នាំចេញផ្សាយ",
  runtime: "រយៈពេល",
  watchNow: "មើលឥឡូវ",
  addToList: "បន្ថែមទៅបញ្ជី",
  inMyList: "មានក្នុងបញ្ជី",
  readStory: "មើលព័ត៌មាន",
  newEveryWeek: "ថ្មីរៀងរាល់សប្ដាហ៍",
  email: "អាសយដ្ឋានអ៊ីមែល",
  getUpdates: "ទទួលព័ត៌មានថ្មី",
  collection: "បណ្ណាល័យភាពយន្ត",
  findNextStory: "ស្វែងរករឿងបន្ទាប់របស់អ្នក",
  moviesIntro:
    "ស្វែងរកភាពយន្តដែលបានជ្រើសរើសសម្រាប់គុណភាព សិល្បៈ និងអារម្មណ៍ដែលនៅសល់យូរ។",
  yourCollection: "បណ្ណាល័យរបស់អ្នក",
  filmsYouLove: "ភាពយន្តដែលអ្នកស្រឡាញ់",
  favouritesCopy: "បណ្ណាល័យផ្ទាល់ខ្លួននៃរឿងដែលអ្នកចង់ត្រឡប់មកមើលម្ដងទៀត។",
  savedLater: "រក្សាទុកសម្រាប់ពេលក្រោយ",
  yourWatchlist: "បញ្ជីមើលរបស់អ្នក",
  watchlistCopy: "ភាពយន្តទាំងអស់ដែលអ្នកចង់មើល រក្សាទុកនៅកន្លែងតែមួយ។",
  noFilms: "រកមិនឃើញភាពយន្ត",
  discoverFilms: "ស្វែងរកភាពយន្ត",
  allGenres: "គ្រប់ប្រភេទ",
  topRated: "ពិន្ទុខ្ពស់",
  newest: "ថ្មីបំផុត",
  searchMovies: "ស្វែងរកភាពយន្ត",
  seeAllResults: "មើលលទ្ធផលទាំងអស់",
  company: "ក្រុមហ៊ុន",
  account: "គណនី",
  contact: "ទំនាក់ទំនង",
  createAccount: "បង្កើតគណនី",
  allMovies: "ភាពយន្តទាំងអស់",
  rights: "រក្សាសិទ្ធិគ្រប់យ៉ាង។",
  backTop: "ត្រឡប់ទៅលើ",
  movieNights: "បង្កើតសម្រាប់រាត្រីភាពយន្ត។",
  ourView: "ទស្សនៈរបស់យើង",
  whyExist: "ហេតុអ្វីយើងបង្កើតវា",
  lessScrolling: "រំកិលតិច អារម្មណ៍កាន់តែច្រើន",
  talkToUs: "និយាយជាមួយយើង",
  curatedTitles: "ភាពយន្តបានជ្រើសរើស",
  distinctGenres: "ប្រភេទខុសៗគ្នា",
  reactPowered: "បង្កើតដោយ React",
  startConversation: "ចាប់ផ្ដើមការសន្ទនា",
  getInTouch: "ទាក់ទងមកយើង",
  loveToHear: "យើងរីករាយនឹងស្ដាប់ពីអ្នក",
  basedIn: "ទីតាំង",
  name: "ឈ្មោះ",
  message: "សារ",
  sendMessage: "ផ្ញើសារ",
  join: "ចូលរួមជាមួយ CineVault",
  startCollection: "ចាប់ផ្ដើមបណ្ណាល័យរបស់អ្នក",
  alreadyMember: "មានគណនីរួចហើយ?",
  returnHome: "ត្រឡប់ទៅទំព័រដើម",
  sceneNotFound: "រកមិនឃើញទំព័រ",
  pageMissing: "ទំព័រដែលអ្នកស្នើសុំមិនមាននៅក្នុងបណ្ណាល័យរបស់យើងទេ។",
  story: "សាច់រឿង",
  aboutFilm: "អំពីភាពយន្ត",
  community: "សហគមន៍",
  viewerReviews: "មតិអ្នកទស្សនា",
  noReviews: "មិនទាន់មានមតិយល់ព្រមទេ។ ចែករំលែកមតិរបស់អ្នកមុនគេ។",
  writeReview: "សរសេរមតិ",
  rating: "ពិន្ទុ",
  review: "មតិ",
  submitReview: "ផ្ញើមតិ",
  director: "អ្នកដឹកនាំ",
  cast: "តួសម្ដែង",
  release: "ឆ្នាំចេញផ្សាយ",
  score: "ពិន្ទុ",
  loading: "កំពុងផ្ទុក CineVault…",
  preparing: "កំពុងរៀបចំបណ្ណាល័យ។",
  password: "ពាក្យសម្ងាត់",
  forgotPassword: "ភ្លេចពាក្យសម្ងាត់?",
  keepSignedIn: "រក្សាការចូលគណនី",
  signingIn: "កំពុងចូល…",
  welcomeBack: "សូមស្វាគមន៍មកវិញ",
  signInWorkspace: "ចូលទៅកាន់កន្លែងការងាររបស់អ្នក",
  continueWatching: "បន្តការមើល",
  becauseWatched: "ដោយសារអ្នកបានមើល",
  topTen: "ភាពយន្តកំពូលទាំង ១០ នៅ CineVault ថ្ងៃនេះ",
  everyoneWatching: "អ្វីដែលគ្រប់គ្នាកំពុងមើល",
  newReleases: "ភាពយន្តចេញថ្មី",
  freshVault: "ថ្មីពីបណ្ណាល័យ",
  trendingNow: "កំពុងពេញនិយមឥឡូវនេះ",
  youMightLike: "ដែលអ្នកប្រហែលជាចូលចិត្ត",
  scienceFiction: "វិទ្យាសាស្ត្រប្រឌិត",
  drama: "រឿងជីវិត",
  thriller: "រន្ធត់",
  action: "សកម្មភាព",
  animation: "គំនូរជីវចល",
  crime: "ឧក្រិដ្ឋកម្ម",
  aboutHeading: "ភាពយន្តល្អ នឹងស្វែងរកអ្នកឃើញ។",
  aboutCopy:
    "CineVault គឺជាបទពិសោធន៍ស្វែងរកភាពយន្ត ដែលបង្កើតឡើងដើម្បីធ្វើឱ្យការជ្រើសរើសអ្វីមួយមើលកាន់តែងាយស្រួល និងមានអារម្មណ៍ល្អ។",
  contactHeading: "និយាយគ្នាអំពីភាពយន្ត។",
  contactCopy: "មានសំណួរ មតិយោបល់ ឬភាពយន្តដែលយើងគួរដឹង? សូមផ្ញើសារមកយើង។",
  newsletterTitle: "ភាពយន្តដែលអ្នកចូលចិត្តបន្ទាប់ កំពុងរង់ចាំ។",
  newsletterCopy:
    "ទទួលព័ត៌មានភាពយន្តថ្មី និងការណែនាំដែលបានជ្រើសរើសដោយយកចិត្តទុកដាក់។",
  footerCopy:
    "ភាពយន្តដែលបានជ្រើសរើសសម្រាប់អ្នកដែលជឿថា រឿងល្អៗគួរត្រូវបានរកឃើញ។",
  aboutHeroCopy:
    "យើងជ្រើសរើសភាពយន្តដែលមានសាច់រឿងល្អ រូបភាពស្រស់ស្អាត និងអារម្មណ៍ដែលនៅជាមួយអ្នកយូរ។",
  ourApproach: "វិធីសាស្ត្ររបស់យើង",
  humanCurated: "ជ្រើសរើសដោយមនុស្ស",
  humanCuratedCopy:
    "ភាពយន្តនីមួយៗត្រូវបានជ្រើសរើសដោយយកចិត្តទុកដាក់ មិនមែនដោយក្បួនដោះស្រាយទេ។",
  qualityFirst: "គុណភាពជាមុន",
  qualityFirstCopy: "យើងផ្តោតលើសាច់រឿង សិល្បៈ និងស្នាដៃដែលមានតម្លៃយូរអង្វែង។",
  simpleDiscovery: "ការស្វែងរកងាយស្រួល",
  simpleDiscoveryCopy:
    "រចនាឡើងដើម្បីជួយអ្នករកឃើញភាពយន្តល្អ ដោយមិនចាំបាច់រំកិលគ្មានទីបញ្ចប់។",
  beginConversation: "តើមានភាពយន្តល្អដែលយើងគួរដឹងទេ?",
  beginConversationCopy: "ចែករំលែកការណែនាំ មតិយោបល់ ឬនិយាយជាមួយយើងអំពីភាពយន្ត។",
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useLocalStorage("cinevault-language", "en");
  useEffect(() => {
    document.documentElement.lang = language === "km" ? "km" : "en";
  }, [language]);
  const value = useMemo(
    () => ({
      language,
      toggleLanguage: () => setLanguage(language === "km" ? "en" : "km"),
      t: (key, fallback = key) =>
        language === "km" ? translations[key] || fallback : fallback,
    }),
    [language, setLanguage],
  );
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}
